##################################################
# Zek Chak: LEMP on Ubuntu 20.04
##################################################
---
- hosts: all
  become: true
  vars_files:
    # - vars/dev.yml
    # - vars/uat.yml

  tasks:
    - name: Upgrade system
      apt: upgrade=dist update_cache=yes

    - name: Install Prerequisites
      apt: name={{ item }} update_cache=yes state=latest force_apt_get=yes
      loop: [ 'aptitude' ]

    - name: Install LEMP Packages & Let's Encrypt certbot
      apt:
        state: latest
        update_cache: yes
        pkg: 
        - nginx
        - python3-pymysql
        - php-fpm
        - php-mysql
        - php-simplexml
        - php-curl
        - build-essential
        - php-pear
        - php-dev
        - libmcrypt-dev
        - certbot
        - python3-certbot-nginx

    - name: Install mySQL server
      apt: name={{ item }} update_cache=yes state=latest
      loop: [ 'mysql-server']
      when: not external_db

    - name: Install mySQL client
      apt: name={{ item }} update_cache=yes state=latest
      loop: [ 'mysql-client']
      when: external_db

    - name: Update PECL channels for php-mcrypt
      shell: "pecl channel-update pecl.php.net"

    - name: Update PECL channels for php-mcrypt step 2
      shell: "pecl update-channels"

    - name: Check if mcrypt is installed
      shell: "pecl list | grep mcrypt"
      register: mcrypt_installed
      ignore_errors: true
    
    # - debug:
    #     var: mcrypt_installed.stdout

    - name: Install mcrypt extension
      shell: 'printf "\n" | pecl install mcrypt'
      when: mcrypt_installed.stdout == ""

    - name: Add extension to cli/php.ini
      lineinfile:
        path: /etc/php/7.4/cli/php.ini
        regexp: '^extension=mycrypt\.so'
        insertafter: "^;extension=xsl"
        line: "extension=mycrypt.so"

    - name: Add extension to fpm/php.ini
      lineinfile:
        path: /etc/php/7.4/fpm/php.ini
        regexp: '^extension=mycrypt\.so'
        insertafter: "^;extension=xsl"
        line: "extension=mycrypt.so"

    - name: Sets the root password 
      mysql_user: 
        name: root 
        password: "{{ mysql_root_password }}"
        login_unix_socket: /var/run/mysqld/mysqld.sock
      when: not external_db

    - name: Create .my.cnf
      template:
        src: "files/client.my.cnf.j2"
        dest: "/root/.my.cnf"
        owner: root
        group: root
        mode: 0600 

    - name: Removes all anonymous user accounts
      community.mysql.mysql_user:
        login_host: "{{ mysql_host }}"
        name: ''
        host_all: yes
        state: absent
        login_user: "{{ mysql_root_user }}"
        login_password: "{{ mysql_root_password }}"

    - name: Removes the MySQL test database
      community.mysql.mysql_db:
        login_host: "{{ mysql_host }}"
        name: test 
        state: absent
        login_user: "{{ mysql_root_user }}"
        login_password: "{{ mysql_root_password }}"

    - name: Creates database for WordPress
      community.mysql.mysql_db:
        login_host: "{{ mysql_host }}"
        name: "{{ mysql_db }}"
        state: present
        login_user: "{{ mysql_root_user }}"
        login_password: "{{ mysql_root_password }}"
      tags: [ mysql ]

    - name: Create database user with password and all database privileges
      community.mysql.mysql_user:
        login_host: "{{ mysql_host }}"
        host: "{{ external_db | ternary('%', 'localhost') }}"
        name: "{{ mysql_user }}"
        password: "{{ mysql_password }}"
        priv: "{{ mysql_db }}.*:ALL"
        state: present
        login_user: "{{ mysql_root_user }}"
        login_password: "{{ mysql_root_password }}"
      tags: [ mysql ]

# UFW Configuration
    - name: "UFW - Allow HTTP on port {{ http_port }}"
      ufw:
        rule: allow
        port: "{{ http_port }}"
        proto: tcp

# UFW Configuration HTTPS
    - name: "UFW - Allow HTTPS on port {{ https_port }}"
      ufw:
        rule: allow
        port: "{{ https_port }}"
        proto: tcp

# UFW Allow SSH
    - name: UFW - OpenSSH
      ufw:
        rule: allow
        name: OpenSSH

# # UFW Allow MySQL
#     - name: UFW - OpenSSH
#       ufw:
#         rule: allow
#         port: '3306'
#         proto: tcp
#       when: external_db

# Enable UFW
    - name: Enable UFW
      ufw:
        state: enabled

# WordPress Configuration
    - name: Create document root
      file:
        path: "/var/www/{{ http_host }}"
        state: directory
        owner: "www-data"
        group: "www-data"
        mode: '0755'
      tags: [ wordpress ]

    - name: Download and unpack latest WordPress
      unarchive:
        src: https://wordpress.org/latest.tar.gz
        dest: "/var/www/{{ http_host }}"
        remote_src: yes
        creates: "/var/www/{{ http_host }}/wordpress"
      tags: [ wordpress ]

    - name: add page to do PHP debugging
      template:
        src: "files/phpdebug.php.j2"
        dest: "/var/www/{{ http_host }}/wordpress/jamdebug-BNpvfEt8SX.php"
      when: php_debug_page


    - name: Set up wp-config
      template:
        src: "files/wp-config.php.j2"
        dest: "/var/www/{{ http_host }}/wordpress/wp-config.php"
      tags: [ wordpress ]

    # Nginx Configuration
    - name: Sets Nginx certbot challenge snippet file
      template:
        src: "files/letsencrypt-acme-challenge.conf.j2"
        dest: "/etc/nginx/snippets/letsencrypt-acme-challenge.conf"

    - name: Sets Nginx conf file
      template:
        src: "files/nginx.conf.j2"
        dest: "/etc/nginx/sites-available/{{ http_conf }}"

    - name: Enables new site
      file:
        src: "/etc/nginx/sites-available/{{ http_conf }}"
        dest: "/etc/nginx/sites-enabled/{{ http_conf }}"
        state: link
      notify: Reload Nginx
    
    - name: Removes "default" site
      file:
        path: "/etc/nginx/sites-enabled/default"
        state: absent
      notify: Reload Nginx

    # Let's Encrypt Configuration
    # Comment this out first until DNS has changed
    - name: Generate new certificate.
      shell: "certbot certonly --nginx --noninteractive --agree-tos --email {{ certbot_admin_email }} -d {{ http_host }}"
      when: (not http_host_is_root) and enable_https

    - name: Generate new certificate.
      shell: "certbot certonly --nginx --noninteractive --agree-tos --email {{ certbot_admin_email }} -d {{ http_host }} -d www.{{ http_host }}"
      when: http_host_is_root and enable_https
      # with_items: "{{ letsencrypt_cert.results }}"

    # Append lines to nginx conf after getting letsencrypt cert
    - name: Add SSL settings
      blockinfile:
        path: "/etc/nginx/sites-available/{{ http_conf }}"
        insertafter: "# SSH settings below here"
        block: |
          listen 443 ssl;
          ssl_certificate /etc/letsencrypt/live/{{ http_host }}/fullchain.pem;
          ssl_certificate_key /etc/letsencrypt/live/{{ http_host }}/privkey.pem;
          include /etc/letsencrypt/options-ssl-nginx.conf;
          ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;
      notify: Reload Nginx
      when: enable_https

    # Git
    - name: add id_rsa to ubuntu to do git pull
      template:
        src: "files/id_rsa_gituser.j2"
        dest: "/home/ubuntu/.ssh/id_rsa"
        owner: ubuntu
        group: ubuntu
        mode: 0600

    - name: add id_rsa to root to do git pull
      template:
        src: "files/id_rsa_gituser.j2"
        dest: "/root/.ssh/id_rsa"
        owner: root
        group: root
        mode: 0600
    
    - name: add gitconfig for root user
      template:
        src: "files/gitconfig.j2"
        dest: "/root/.gitconfig"
        owner: root
        group: root
    
    - name: Git init
      shell: 
        cmd: git init
        chdir: "/var/www/{{ http_host }}/wordpress"
    
    - name: Check if git remote exists
      shell:
        cmd: git remote
        chdir: "/var/www/{{ http_host }}/wordpress"
      register: git_remotes

    - name: Git remote add
      shell: 
        cmd: git remote add origin git@bitbucket.org:justaftermidnight247/gic-wp-educational-source.git
        chdir: "/var/www/{{ http_host }}/wordpress"
      when: git_remotes.stdout == ""
    
    - name: add ubuntu to www-data group
      user:
        name: ubuntu
        groups: www-data
        append: yes

    - name: Set ownership
      file:
        path: "/var/www/{{ http_host }}"
        state: directory
        recurse: yes
        owner: www-data
        group: www-data
      tags: [ wordpress ]

    # - name: Set ownership for plugins
    #   file:
    #     path: "/var/www/{{ http_host }}/wordpress/wp-content"
    #     state: directory
    #     recurse: yes
    #     owner: www-data
    #     group: www-data
    #   tags: [ wordpress ]

    - name: Set permissions for directories
      shell: "/usr/bin/find /var/www/{{ http_host }}/wordpress/ -type d -exec chmod 750 {} \\;"
      tags: [ wordpress ]

    - name: Set permissions for files
      shell: "/usr/bin/find /var/www/{{ http_host }}/wordpress/ -type f -exec chmod 640 {} \\;"
      tags: [ wordpress ]

  handlers:
    - name: Reload Nginx
      service:
        name: nginx
        state: reloaded

    - name: Restart Nginx
      service:
        name: nginx
        state: restarted
