##################################################
# For GIC-WPE: Git push from source
##################################################
---
- hosts: all
  become: true
  vars_files:
    # - vars/default.yml

  tasks:
    - name: Git checkout source
      shell: 
        cmd: git checkout {{ source_branch }}
        chdir: "{{ wp_dir }}"

    - name: Git status
      shell: 
        cmd: git status | grep 'nothing to commit, working tree clean'
        chdir: "{{ wp_dir }}"
      register: git_status_output
      ignore_errors: true
  
    - debug:
        var: git_status_output.stdout

    - name: Git add .
      shell: 
        cmd: git add .
        chdir: "{{ wp_dir }}"
      when: git_status_output.stdout == ""
        
    - name: Git commit
      shell: 
        cmd: git commit -m "{{ commit_message }}"
        chdir: "{{ wp_dir }}"
      when: git_status_output.stdout == ""

    - name: Git push to origin
      shell: 
        cmd: git push origin {{ source_branch }}
        chdir: "{{ wp_dir }}"
      when: git_status_output.stdout == ""

    - name: Git checkout target
      shell: 
        cmd: git checkout {{ target_branch }}
        chdir: "{{ wp_dir }}"

    - name: Git pull from origin
      shell: 
        cmd: git pull origin {{ target_branch }}
        chdir: "{{ wp_dir }}"

    - name: Git merge source into target
      shell: 
        cmd: git merge {{ source_branch }}
        chdir: "{{ wp_dir }}"

    - name: Git push target to origin
      shell: 
        cmd: git push origin {{ target_branch }}
        chdir: "{{ wp_dir }}"

    - name: Git checkout source
      shell: 
        cmd: git checkout {{ source_branch }}
        chdir: "{{ wp_dir }}"

    - name: Set ownership for wp
      file:
        path: "{{ wp_dir }}"
        state: directory
        recurse: yes
        owner: www-data
        group: www-data

    # - name: Set ownership for plugins
    #   file:
    #     path: "{{ wp_dir }}/wp-content"
    #     state: directory
    #     recurse: yes
    #     owner: www-data
    #     group: www-data

    - name: Set permissions for directories
      shell: "/usr/bin/find {{ wp_dir }}/ -type d -exec chmod 750 {} \\;"

    - name: Set permissions for files
      shell: "/usr/bin/find {{ wp_dir }}/ -type f -exec chmod 640 {} \\;"



