---
#System Settings
php_modules: [ 'php-curl', 'php-gd', 'php-mbstring', 'php-xml', 'php-xmlrpc', 'php-soap', 'php-intl', 'php-zip' ]

# dbmasteruser
mysql_root_user: "dbmasteruser"
mysql_root_password: "2BKjSKtkjMAG72mZHBXw8V5u8"
mysql_host: "ls-4bfe52bbcb300be99098dedd7cd9333efdde59ea.cy2gwvojh4mq.ap-southeast-1.rds.amazonaws.com"
mysql_db: "gicwp"
mysql_user: "gicwp"
mysql_password: "8rc9TNsfrUxqon5zunnoWNjH8"
http_host: "gicwpe-uat.jam247.dev"
http_host_is_root: true
http_conf: "gicwpe-uat.jam247.dev.conf"
http_port: "80"
https_port: "443"

certbot_admin_email: "zek.chak@justaftermidnight.io"